export const PAGE_CONFIG = [
  { key: "default", isHasUnderground: true, label: "默认页面" },
  //生产调度
  { key: "scdd", isHasUnderground: true, label: "生产调度" },
  { key: "scts", isHasUnderground: true, label: "生产态势" },
  { key: "szls", isHasUnderground: true, label: "数字孪生" },
  { key: "ckjd", isHasUnderground: true, label: "采矿进度" },
  //安全预防
  { key: "gdxt", isHasUnderground: true, label: "供电系统" },
  { key: "fps", isHasUnderground: true, label: "防排水" },
  //
  { key: "scyf", isHasUnderground: true, label: "双重预防" },
  { key: "tmdz", isHasUnderground: true, label: "透明地质" },
  { key: "tmdzgy", isHasUnderground: true, label: "工艺展示" },
  { key: "drill", isHasUnderground: false, label: "钻孔数据" },
  { key: "block", isHasUnderground: false, label: "块体模型" },
  { key: "spjk", isHasUnderground: true, label: "视频监控" },
  { key: "fmh", isHasUnderground: true, label: "防灭火" },
  { key: "clgl", isHasUnderground: true, label: "储量管理" },
  { key: "emergency_rescue", isHasUnderground: false, label: "应急救援" },
  { key: "khgl", isHasUnderground: true, label: "客户管理" },
  { key: "bpjc", isHasUnderground: false, label: "边坡预警" },
  { key: "file", isHasUnderground: false, label: "会议管理" },
  { key: "bjms", isHasUnderground: true, label: "编辑绘图" },
  { key: "mine", isHasUnderground: false, label: "3DMine" },
  { key: "xwyq", isHasUnderground: false, label: "智慧园区" },
  { key: "zncb", isHasUnderground: false, label: "智能穿爆" },
  { key: "xmjj", isHasUnderground: false, label: "智慧园区" },
  { key: "zhzs", isHasUnderground: false, label: "综合展示" },
  { key: "rydw", isHasUnderground: false, label: "人员定位" },
  { key: "wrjs", isHasUnderground: false, label: "无人驾驶" },
  { key: "fpz", isHasUnderground: false, label: "三防系统" },
  { key: "fxgk", isHasUnderground: false, label: "风险管控" },
  { key: "zhsw", isHasUnderground: false, label: "智慧水务" },
  { key: "miningplan", isHasUnderground: false, label: "采矿计划" },
  { key: "powersupplymanagent", isHasUnderground: false, label: "供电管理" },
];
