export * from "./environment";
export * from "./map-menu";

import { utils } from "3dm-im-components";

// ?????? 3dm-im-components utils ??????? 3dmine ???
export const {
  message,
  cookieCache,
  localCache,
  sessionCache,
  htmlToPdf,
  getAudioTag,
  getImageTag,
  getVideoTag,
  formatUTC,
  getBeforeDate,
  getDateObj,
  getLastMonth,
  fullScreen,
  isAsyncFunction,
  mergeAndFilterArr,
  OBJDeepClone,
  getParamOnURL,
  formatUrlParam,
  debounce,
  datePickerChange,
  isVideo,
  isImage,
  isAudio,
  fileSizeFormat,
  TreeDataToMap,
  getImageInfoByBase64DataURL,
  openHelpCsdnOnDev,
  isExternal,
  getPageTitle,
  getCrc32,
  downloadFile,
  uint8ArrayToBase64,
  base64Decode,
  getCutFileInfo,
  appendBuffer,
  initModelLargerFileSocket,
  formatterPieLegend,
  joinName,
  getFirstAndLastDayOfMonth,
  getCurrentPageMaxZIndex,
  mergeObjects,
  mapMenus2Routes,
  getFileExtension,
  emptyFn,
  useSubscribe,
  generateDayOptions,
} = utils;
